name: Auto Deploy to MonsterASP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build & Publish App
        run: dotnet publish "OzBI Portal CRM.csproj" -c Release -o ./publish

      - name: FTP Deploy to MonsterASP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: site83172.siteasp.net
          username: site83172
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /wwwroot/
          security: loose
          log-level: verbose
